a.out: myProgram.o StackImplementation.o
	gcc myProgram.o StackImplementation.o

myProgram.o: myProgram.c StackInterface.h StackType.h
	gcc -c myProgram.c

StackImplementation.o: StackImplementation.c StackInterface.h StackType.h
	gcc -c StackImplementation.c


















